// Code generated by protoc-gen-go.
// source: controldb.proto
// DO NOT EDIT!

/*
Package controldb_proto is a generated protocol buffer package.

It is generated from these files:
	controldb.proto

It has these top-level messages:
	DeviceKey
	Device
	CreateDeviceResponse
	DeleteDeviceResponse
	AllDevices
	ListDeviceRequest
	ServiceKey
	Service
	CreateServiceResponse
	DeleteServiceResponse
	AllServices
	ListServiceRequest
	ServiceAttrKey
	ServiceAttr
	CreateServiceAttrResponse
	DeleteServiceAttrResponse
	UpdateServiceAttrRequest
	UpdateServiceAttrResponse
	VolumeKey
	Volume
	CreateVolumeResponse
	DeleteVolumeResponse
	ListVolumeRequest
	UpdateVolumeRequest
	UpdateVolumeResponse
	MemberConfig
	ConfigFileKey
	ConfigFile
	CreateConfigFileResponse
	DeleteConfigFileResponse
*/
package controldb_proto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DeviceKey struct {
	ClusterName string `protobuf:"bytes,1,opt,name=clusterName" json:"clusterName,omitempty"`
	DeviceName  string `protobuf:"bytes,2,opt,name=deviceName" json:"deviceName,omitempty"`
}

func (m *DeviceKey) Reset()                    { *m = DeviceKey{} }
func (m *DeviceKey) String() string            { return proto.CompactTextString(m) }
func (*DeviceKey) ProtoMessage()               {}
func (*DeviceKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DeviceKey) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *DeviceKey) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

type Device struct {
	ClusterName string `protobuf:"bytes,1,opt,name=clusterName" json:"clusterName,omitempty"`
	DeviceName  string `protobuf:"bytes,2,opt,name=deviceName" json:"deviceName,omitempty"`
	ServiceName string `protobuf:"bytes,3,opt,name=serviceName" json:"serviceName,omitempty"`
}

func (m *Device) Reset()                    { *m = Device{} }
func (m *Device) String() string            { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()               {}
func (*Device) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Device) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *Device) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *Device) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type CreateDeviceResponse struct {
}

func (m *CreateDeviceResponse) Reset()                    { *m = CreateDeviceResponse{} }
func (m *CreateDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateDeviceResponse) ProtoMessage()               {}
func (*CreateDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type DeleteDeviceResponse struct {
}

func (m *DeleteDeviceResponse) Reset()                    { *m = DeleteDeviceResponse{} }
func (m *DeleteDeviceResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteDeviceResponse) ProtoMessage()               {}
func (*DeleteDeviceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type AllDevices struct {
	Devices []*Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty"`
}

func (m *AllDevices) Reset()                    { *m = AllDevices{} }
func (m *AllDevices) String() string            { return proto.CompactTextString(m) }
func (*AllDevices) ProtoMessage()               {}
func (*AllDevices) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AllDevices) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type ListDeviceRequest struct {
	ClusterName string `protobuf:"bytes,1,opt,name=clusterName" json:"clusterName,omitempty"`
}

func (m *ListDeviceRequest) Reset()                    { *m = ListDeviceRequest{} }
func (m *ListDeviceRequest) String() string            { return proto.CompactTextString(m) }
func (*ListDeviceRequest) ProtoMessage()               {}
func (*ListDeviceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ListDeviceRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

type ServiceKey struct {
	ClusterName string `protobuf:"bytes,1,opt,name=clusterName" json:"clusterName,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=serviceName" json:"serviceName,omitempty"`
}

func (m *ServiceKey) Reset()                    { *m = ServiceKey{} }
func (m *ServiceKey) String() string            { return proto.CompactTextString(m) }
func (*ServiceKey) ProtoMessage()               {}
func (*ServiceKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ServiceKey) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ServiceKey) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

type Service struct {
	ClusterName string `protobuf:"bytes,1,opt,name=clusterName" json:"clusterName,omitempty"`
	ServiceName string `protobuf:"bytes,2,opt,name=serviceName" json:"serviceName,omitempty"`
	ServiceUUID string `protobuf:"bytes,3,opt,name=serviceUUID" json:"serviceUUID,omitempty"`
}

func (m *Service) Reset()                    { *m = Service{} }
func (m *Service) String() string            { return proto.CompactTextString(m) }
func (*Service) ProtoMessage()               {}
func (*Service) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Service) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *Service) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *Service) GetServiceUUID() string {
	if m != nil {
		return m.ServiceUUID
	}
	return ""
}

type CreateServiceResponse struct {
}

func (m *CreateServiceResponse) Reset()                    { *m = CreateServiceResponse{} }
func (m *CreateServiceResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateServiceResponse) ProtoMessage()               {}
func (*CreateServiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type DeleteServiceResponse struct {
}

func (m *DeleteServiceResponse) Reset()                    { *m = DeleteServiceResponse{} }
func (m *DeleteServiceResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteServiceResponse) ProtoMessage()               {}
func (*DeleteServiceResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

type AllServices struct {
	Services []*Service `protobuf:"bytes,1,rep,name=services" json:"services,omitempty"`
}

func (m *AllServices) Reset()                    { *m = AllServices{} }
func (m *AllServices) String() string            { return proto.CompactTextString(m) }
func (*AllServices) ProtoMessage()               {}
func (*AllServices) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *AllServices) GetServices() []*Service {
	if m != nil {
		return m.Services
	}
	return nil
}

type ListServiceRequest struct {
	ClusterName string `protobuf:"bytes,1,opt,name=clusterName" json:"clusterName,omitempty"`
}

func (m *ListServiceRequest) Reset()                    { *m = ListServiceRequest{} }
func (m *ListServiceRequest) String() string            { return proto.CompactTextString(m) }
func (*ListServiceRequest) ProtoMessage()               {}
func (*ListServiceRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ListServiceRequest) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

type ServiceAttrKey struct {
	ServiceUUID string `protobuf:"bytes,1,opt,name=serviceUUID" json:"serviceUUID,omitempty"`
}

func (m *ServiceAttrKey) Reset()                    { *m = ServiceAttrKey{} }
func (m *ServiceAttrKey) String() string            { return proto.CompactTextString(m) }
func (*ServiceAttrKey) ProtoMessage()               {}
func (*ServiceAttrKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ServiceAttrKey) GetServiceUUID() string {
	if m != nil {
		return m.ServiceUUID
	}
	return ""
}

type ServiceAttr struct {
	ServiceUUID string `protobuf:"bytes,1,opt,name=serviceUUID" json:"serviceUUID,omitempty"`
	// same with db.ServiceAttr.ServiceStatus: CREATING, ACTIVE, DELETING, DELETED
	ServiceStatus string `protobuf:"bytes,2,opt,name=serviceStatus" json:"serviceStatus,omitempty"`
	LastModified  int64  `protobuf:"varint,3,opt,name=lastModified" json:"lastModified,omitempty"`
	Replicas      int64  `protobuf:"varint,4,opt,name=replicas" json:"replicas,omitempty"`
	VolumeSizeGB  int64  `protobuf:"varint,5,opt,name=volumeSizeGB" json:"volumeSizeGB,omitempty"`
	ClusterName   string `protobuf:"bytes,6,opt,name=clusterName" json:"clusterName,omitempty"`
	ServiceName   string `protobuf:"bytes,7,opt,name=serviceName" json:"serviceName,omitempty"`
	DeviceName    string `protobuf:"bytes,8,opt,name=deviceName" json:"deviceName,omitempty"`
	// whether the service has the strict membership, such as database replicas.
	// if yes, each volume will be assigned a member name and registered to DNS.
	// in aws, DNS will be Route53.
	HasStrictMembership bool   `protobuf:"varint,9,opt,name=hasStrictMembership" json:"hasStrictMembership,omitempty"`
	DomainName          string `protobuf:"bytes,10,opt,name=domainName" json:"domainName,omitempty"`
	HostedZoneID        string `protobuf:"bytes,11,opt,name=hostedZoneID" json:"hostedZoneID,omitempty"`
}

func (m *ServiceAttr) Reset()                    { *m = ServiceAttr{} }
func (m *ServiceAttr) String() string            { return proto.CompactTextString(m) }
func (*ServiceAttr) ProtoMessage()               {}
func (*ServiceAttr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ServiceAttr) GetServiceUUID() string {
	if m != nil {
		return m.ServiceUUID
	}
	return ""
}

func (m *ServiceAttr) GetServiceStatus() string {
	if m != nil {
		return m.ServiceStatus
	}
	return ""
}

func (m *ServiceAttr) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

func (m *ServiceAttr) GetReplicas() int64 {
	if m != nil {
		return m.Replicas
	}
	return 0
}

func (m *ServiceAttr) GetVolumeSizeGB() int64 {
	if m != nil {
		return m.VolumeSizeGB
	}
	return 0
}

func (m *ServiceAttr) GetClusterName() string {
	if m != nil {
		return m.ClusterName
	}
	return ""
}

func (m *ServiceAttr) GetServiceName() string {
	if m != nil {
		return m.ServiceName
	}
	return ""
}

func (m *ServiceAttr) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *ServiceAttr) GetHasStrictMembership() bool {
	if m != nil {
		return m.HasStrictMembership
	}
	return false
}

func (m *ServiceAttr) GetDomainName() string {
	if m != nil {
		return m.DomainName
	}
	return ""
}

func (m *ServiceAttr) GetHostedZoneID() string {
	if m != nil {
		return m.HostedZoneID
	}
	return ""
}

type CreateServiceAttrResponse struct {
}

func (m *CreateServiceAttrResponse) Reset()                    { *m = CreateServiceAttrResponse{} }
func (m *CreateServiceAttrResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateServiceAttrResponse) ProtoMessage()               {}
func (*CreateServiceAttrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

type DeleteServiceAttrResponse struct {
}

func (m *DeleteServiceAttrResponse) Reset()                    { *m = DeleteServiceAttrResponse{} }
func (m *DeleteServiceAttrResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteServiceAttrResponse) ProtoMessage()               {}
func (*DeleteServiceAttrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type UpdateServiceAttrRequest struct {
	OldAttr *ServiceAttr `protobuf:"bytes,1,opt,name=oldAttr" json:"oldAttr,omitempty"`
	NewAttr *ServiceAttr `protobuf:"bytes,2,opt,name=newAttr" json:"newAttr,omitempty"`
}

func (m *UpdateServiceAttrRequest) Reset()                    { *m = UpdateServiceAttrRequest{} }
func (m *UpdateServiceAttrRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateServiceAttrRequest) ProtoMessage()               {}
func (*UpdateServiceAttrRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *UpdateServiceAttrRequest) GetOldAttr() *ServiceAttr {
	if m != nil {
		return m.OldAttr
	}
	return nil
}

func (m *UpdateServiceAttrRequest) GetNewAttr() *ServiceAttr {
	if m != nil {
		return m.NewAttr
	}
	return nil
}

type UpdateServiceAttrResponse struct {
}

func (m *UpdateServiceAttrResponse) Reset()                    { *m = UpdateServiceAttrResponse{} }
func (m *UpdateServiceAttrResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateServiceAttrResponse) ProtoMessage()               {}
func (*UpdateServiceAttrResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{17} }

type VolumeKey struct {
	ServiceUUID string `protobuf:"bytes,1,opt,name=serviceUUID" json:"serviceUUID,omitempty"`
	VolumeID    string `protobuf:"bytes,2,opt,name=volumeID" json:"volumeID,omitempty"`
}

func (m *VolumeKey) Reset()                    { *m = VolumeKey{} }
func (m *VolumeKey) String() string            { return proto.CompactTextString(m) }
func (*VolumeKey) ProtoMessage()               {}
func (*VolumeKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{18} }

func (m *VolumeKey) GetServiceUUID() string {
	if m != nil {
		return m.ServiceUUID
	}
	return ""
}

func (m *VolumeKey) GetVolumeID() string {
	if m != nil {
		return m.VolumeID
	}
	return ""
}

type Volume struct {
	ServiceUUID         string `protobuf:"bytes,1,opt,name=serviceUUID" json:"serviceUUID,omitempty"`
	VolumeID            string `protobuf:"bytes,2,opt,name=volumeID" json:"volumeID,omitempty"`
	LastModified        int64  `protobuf:"varint,3,opt,name=lastModified" json:"lastModified,omitempty"`
	DeviceName          string `protobuf:"bytes,4,opt,name=deviceName" json:"deviceName,omitempty"`
	AvailableZone       string `protobuf:"bytes,5,opt,name=availableZone" json:"availableZone,omitempty"`
	TaskID              string `protobuf:"bytes,6,opt,name=taskID" json:"taskID,omitempty"`
	ContainerInstanceID string `protobuf:"bytes,7,opt,name=containerInstanceID" json:"containerInstanceID,omitempty"`
	ServerInstanceID    string `protobuf:"bytes,8,opt,name=serverInstanceID" json:"serverInstanceID,omitempty"`
	// MemberName would be empty if service doesn't require the strict membership
	MemberName string          `protobuf:"bytes,9,opt,name=memberName" json:"memberName,omitempty"`
	Configs    []*MemberConfig `protobuf:"bytes,10,rep,name=configs" json:"configs,omitempty"`
}

func (m *Volume) Reset()                    { *m = Volume{} }
func (m *Volume) String() string            { return proto.CompactTextString(m) }
func (*Volume) ProtoMessage()               {}
func (*Volume) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{19} }

func (m *Volume) GetServiceUUID() string {
	if m != nil {
		return m.ServiceUUID
	}
	return ""
}

func (m *Volume) GetVolumeID() string {
	if m != nil {
		return m.VolumeID
	}
	return ""
}

func (m *Volume) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

func (m *Volume) GetDeviceName() string {
	if m != nil {
		return m.DeviceName
	}
	return ""
}

func (m *Volume) GetAvailableZone() string {
	if m != nil {
		return m.AvailableZone
	}
	return ""
}

func (m *Volume) GetTaskID() string {
	if m != nil {
		return m.TaskID
	}
	return ""
}

func (m *Volume) GetContainerInstanceID() string {
	if m != nil {
		return m.ContainerInstanceID
	}
	return ""
}

func (m *Volume) GetServerInstanceID() string {
	if m != nil {
		return m.ServerInstanceID
	}
	return ""
}

func (m *Volume) GetMemberName() string {
	if m != nil {
		return m.MemberName
	}
	return ""
}

func (m *Volume) GetConfigs() []*MemberConfig {
	if m != nil {
		return m.Configs
	}
	return nil
}

type CreateVolumeResponse struct {
}

func (m *CreateVolumeResponse) Reset()                    { *m = CreateVolumeResponse{} }
func (m *CreateVolumeResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateVolumeResponse) ProtoMessage()               {}
func (*CreateVolumeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{20} }

type DeleteVolumeResponse struct {
}

func (m *DeleteVolumeResponse) Reset()                    { *m = DeleteVolumeResponse{} }
func (m *DeleteVolumeResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteVolumeResponse) ProtoMessage()               {}
func (*DeleteVolumeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{21} }

type ListVolumeRequest struct {
	ServiceUUID string `protobuf:"bytes,1,opt,name=serviceUUID" json:"serviceUUID,omitempty"`
}

func (m *ListVolumeRequest) Reset()                    { *m = ListVolumeRequest{} }
func (m *ListVolumeRequest) String() string            { return proto.CompactTextString(m) }
func (*ListVolumeRequest) ProtoMessage()               {}
func (*ListVolumeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{22} }

func (m *ListVolumeRequest) GetServiceUUID() string {
	if m != nil {
		return m.ServiceUUID
	}
	return ""
}

type UpdateVolumeRequest struct {
	OldVol *Volume `protobuf:"bytes,1,opt,name=oldVol" json:"oldVol,omitempty"`
	NewVol *Volume `protobuf:"bytes,2,opt,name=newVol" json:"newVol,omitempty"`
}

func (m *UpdateVolumeRequest) Reset()                    { *m = UpdateVolumeRequest{} }
func (m *UpdateVolumeRequest) String() string            { return proto.CompactTextString(m) }
func (*UpdateVolumeRequest) ProtoMessage()               {}
func (*UpdateVolumeRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{23} }

func (m *UpdateVolumeRequest) GetOldVol() *Volume {
	if m != nil {
		return m.OldVol
	}
	return nil
}

func (m *UpdateVolumeRequest) GetNewVol() *Volume {
	if m != nil {
		return m.NewVol
	}
	return nil
}

type UpdateVolumeResponse struct {
}

func (m *UpdateVolumeResponse) Reset()                    { *m = UpdateVolumeResponse{} }
func (m *UpdateVolumeResponse) String() string            { return proto.CompactTextString(m) }
func (*UpdateVolumeResponse) ProtoMessage()               {}
func (*UpdateVolumeResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{24} }

type MemberConfig struct {
	FileName string `protobuf:"bytes,1,opt,name=fileName" json:"fileName,omitempty"`
	FileID   string `protobuf:"bytes,2,opt,name=fileID" json:"fileID,omitempty"`
	FileMD5  string `protobuf:"bytes,3,opt,name=fileMD5" json:"fileMD5,omitempty"`
}

func (m *MemberConfig) Reset()                    { *m = MemberConfig{} }
func (m *MemberConfig) String() string            { return proto.CompactTextString(m) }
func (*MemberConfig) ProtoMessage()               {}
func (*MemberConfig) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{25} }

func (m *MemberConfig) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *MemberConfig) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *MemberConfig) GetFileMD5() string {
	if m != nil {
		return m.FileMD5
	}
	return ""
}

type ConfigFileKey struct {
	ServiceUUID string `protobuf:"bytes,1,opt,name=serviceUUID" json:"serviceUUID,omitempty"`
	FileID      string `protobuf:"bytes,2,opt,name=fileID" json:"fileID,omitempty"`
}

func (m *ConfigFileKey) Reset()                    { *m = ConfigFileKey{} }
func (m *ConfigFileKey) String() string            { return proto.CompactTextString(m) }
func (*ConfigFileKey) ProtoMessage()               {}
func (*ConfigFileKey) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{26} }

func (m *ConfigFileKey) GetServiceUUID() string {
	if m != nil {
		return m.ServiceUUID
	}
	return ""
}

func (m *ConfigFileKey) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

type ConfigFile struct {
	ServiceUUID  string `protobuf:"bytes,1,opt,name=serviceUUID" json:"serviceUUID,omitempty"`
	FileID       string `protobuf:"bytes,2,opt,name=fileID" json:"fileID,omitempty"`
	FileMD5      string `protobuf:"bytes,3,opt,name=fileMD5" json:"fileMD5,omitempty"`
	FileName     string `protobuf:"bytes,4,opt,name=fileName" json:"fileName,omitempty"`
	LastModified int64  `protobuf:"varint,5,opt,name=lastModified" json:"lastModified,omitempty"`
	Content      string `protobuf:"bytes,6,opt,name=content" json:"content,omitempty"`
}

func (m *ConfigFile) Reset()                    { *m = ConfigFile{} }
func (m *ConfigFile) String() string            { return proto.CompactTextString(m) }
func (*ConfigFile) ProtoMessage()               {}
func (*ConfigFile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{27} }

func (m *ConfigFile) GetServiceUUID() string {
	if m != nil {
		return m.ServiceUUID
	}
	return ""
}

func (m *ConfigFile) GetFileID() string {
	if m != nil {
		return m.FileID
	}
	return ""
}

func (m *ConfigFile) GetFileMD5() string {
	if m != nil {
		return m.FileMD5
	}
	return ""
}

func (m *ConfigFile) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *ConfigFile) GetLastModified() int64 {
	if m != nil {
		return m.LastModified
	}
	return 0
}

func (m *ConfigFile) GetContent() string {
	if m != nil {
		return m.Content
	}
	return ""
}

type CreateConfigFileResponse struct {
}

func (m *CreateConfigFileResponse) Reset()                    { *m = CreateConfigFileResponse{} }
func (m *CreateConfigFileResponse) String() string            { return proto.CompactTextString(m) }
func (*CreateConfigFileResponse) ProtoMessage()               {}
func (*CreateConfigFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{28} }

type DeleteConfigFileResponse struct {
}

func (m *DeleteConfigFileResponse) Reset()                    { *m = DeleteConfigFileResponse{} }
func (m *DeleteConfigFileResponse) String() string            { return proto.CompactTextString(m) }
func (*DeleteConfigFileResponse) ProtoMessage()               {}
func (*DeleteConfigFileResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{29} }

func init() {
	proto.RegisterType((*DeviceKey)(nil), "controldb_proto.DeviceKey")
	proto.RegisterType((*Device)(nil), "controldb_proto.Device")
	proto.RegisterType((*CreateDeviceResponse)(nil), "controldb_proto.CreateDeviceResponse")
	proto.RegisterType((*DeleteDeviceResponse)(nil), "controldb_proto.DeleteDeviceResponse")
	proto.RegisterType((*AllDevices)(nil), "controldb_proto.AllDevices")
	proto.RegisterType((*ListDeviceRequest)(nil), "controldb_proto.ListDeviceRequest")
	proto.RegisterType((*ServiceKey)(nil), "controldb_proto.ServiceKey")
	proto.RegisterType((*Service)(nil), "controldb_proto.Service")
	proto.RegisterType((*CreateServiceResponse)(nil), "controldb_proto.CreateServiceResponse")
	proto.RegisterType((*DeleteServiceResponse)(nil), "controldb_proto.DeleteServiceResponse")
	proto.RegisterType((*AllServices)(nil), "controldb_proto.AllServices")
	proto.RegisterType((*ListServiceRequest)(nil), "controldb_proto.ListServiceRequest")
	proto.RegisterType((*ServiceAttrKey)(nil), "controldb_proto.ServiceAttrKey")
	proto.RegisterType((*ServiceAttr)(nil), "controldb_proto.ServiceAttr")
	proto.RegisterType((*CreateServiceAttrResponse)(nil), "controldb_proto.CreateServiceAttrResponse")
	proto.RegisterType((*DeleteServiceAttrResponse)(nil), "controldb_proto.DeleteServiceAttrResponse")
	proto.RegisterType((*UpdateServiceAttrRequest)(nil), "controldb_proto.UpdateServiceAttrRequest")
	proto.RegisterType((*UpdateServiceAttrResponse)(nil), "controldb_proto.UpdateServiceAttrResponse")
	proto.RegisterType((*VolumeKey)(nil), "controldb_proto.VolumeKey")
	proto.RegisterType((*Volume)(nil), "controldb_proto.Volume")
	proto.RegisterType((*CreateVolumeResponse)(nil), "controldb_proto.CreateVolumeResponse")
	proto.RegisterType((*DeleteVolumeResponse)(nil), "controldb_proto.DeleteVolumeResponse")
	proto.RegisterType((*ListVolumeRequest)(nil), "controldb_proto.ListVolumeRequest")
	proto.RegisterType((*UpdateVolumeRequest)(nil), "controldb_proto.UpdateVolumeRequest")
	proto.RegisterType((*UpdateVolumeResponse)(nil), "controldb_proto.UpdateVolumeResponse")
	proto.RegisterType((*MemberConfig)(nil), "controldb_proto.MemberConfig")
	proto.RegisterType((*ConfigFileKey)(nil), "controldb_proto.ConfigFileKey")
	proto.RegisterType((*ConfigFile)(nil), "controldb_proto.ConfigFile")
	proto.RegisterType((*CreateConfigFileResponse)(nil), "controldb_proto.CreateConfigFileResponse")
	proto.RegisterType((*DeleteConfigFileResponse)(nil), "controldb_proto.DeleteConfigFileResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ControlDBService service

type ControlDBServiceClient interface {
	CreateDevice(ctx context.Context, in *Device, opts ...grpc.CallOption) (*CreateDeviceResponse, error)
	GetDevice(ctx context.Context, in *DeviceKey, opts ...grpc.CallOption) (*Device, error)
	DeleteDevice(ctx context.Context, in *DeviceKey, opts ...grpc.CallOption) (*DeleteDeviceResponse, error)
	ListDevices(ctx context.Context, in *ListDeviceRequest, opts ...grpc.CallOption) (ControlDBService_ListDevicesClient, error)
	CreateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*CreateServiceResponse, error)
	GetService(ctx context.Context, in *ServiceKey, opts ...grpc.CallOption) (*Service, error)
	DeleteService(ctx context.Context, in *ServiceKey, opts ...grpc.CallOption) (*DeleteServiceResponse, error)
	ListServices(ctx context.Context, in *ListServiceRequest, opts ...grpc.CallOption) (ControlDBService_ListServicesClient, error)
	CreateServiceAttr(ctx context.Context, in *ServiceAttr, opts ...grpc.CallOption) (*CreateServiceAttrResponse, error)
	GetServiceAttr(ctx context.Context, in *ServiceAttrKey, opts ...grpc.CallOption) (*ServiceAttr, error)
	DeleteServiceAttr(ctx context.Context, in *ServiceAttrKey, opts ...grpc.CallOption) (*DeleteServiceAttrResponse, error)
	UpdateServiceAttr(ctx context.Context, in *UpdateServiceAttrRequest, opts ...grpc.CallOption) (*UpdateServiceAttrResponse, error)
	CreateVolume(ctx context.Context, in *Volume, opts ...grpc.CallOption) (*CreateVolumeResponse, error)
	GetVolume(ctx context.Context, in *VolumeKey, opts ...grpc.CallOption) (*Volume, error)
	DeleteVolume(ctx context.Context, in *VolumeKey, opts ...grpc.CallOption) (*DeleteVolumeResponse, error)
	ListVolumes(ctx context.Context, in *ListVolumeRequest, opts ...grpc.CallOption) (ControlDBService_ListVolumesClient, error)
	UpdateVolume(ctx context.Context, in *UpdateVolumeRequest, opts ...grpc.CallOption) (*UpdateVolumeResponse, error)
	CreateConfigFile(ctx context.Context, in *ConfigFile, opts ...grpc.CallOption) (*CreateConfigFileResponse, error)
	GetConfigFile(ctx context.Context, in *ConfigFileKey, opts ...grpc.CallOption) (*ConfigFile, error)
	DeleteConfigFile(ctx context.Context, in *ConfigFileKey, opts ...grpc.CallOption) (*DeleteConfigFileResponse, error)
}

type controlDBServiceClient struct {
	cc *grpc.ClientConn
}

func NewControlDBServiceClient(cc *grpc.ClientConn) ControlDBServiceClient {
	return &controlDBServiceClient{cc}
}

func (c *controlDBServiceClient) CreateDevice(ctx context.Context, in *Device, opts ...grpc.CallOption) (*CreateDeviceResponse, error) {
	out := new(CreateDeviceResponse)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/CreateDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) GetDevice(ctx context.Context, in *DeviceKey, opts ...grpc.CallOption) (*Device, error) {
	out := new(Device)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/GetDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) DeleteDevice(ctx context.Context, in *DeviceKey, opts ...grpc.CallOption) (*DeleteDeviceResponse, error) {
	out := new(DeleteDeviceResponse)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/DeleteDevice", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) ListDevices(ctx context.Context, in *ListDeviceRequest, opts ...grpc.CallOption) (ControlDBService_ListDevicesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ControlDBService_serviceDesc.Streams[0], c.cc, "/controldb_proto.ControlDBService/ListDevices", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlDBServiceListDevicesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControlDBService_ListDevicesClient interface {
	Recv() (*Device, error)
	grpc.ClientStream
}

type controlDBServiceListDevicesClient struct {
	grpc.ClientStream
}

func (x *controlDBServiceListDevicesClient) Recv() (*Device, error) {
	m := new(Device)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controlDBServiceClient) CreateService(ctx context.Context, in *Service, opts ...grpc.CallOption) (*CreateServiceResponse, error) {
	out := new(CreateServiceResponse)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/CreateService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) GetService(ctx context.Context, in *ServiceKey, opts ...grpc.CallOption) (*Service, error) {
	out := new(Service)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/GetService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) DeleteService(ctx context.Context, in *ServiceKey, opts ...grpc.CallOption) (*DeleteServiceResponse, error) {
	out := new(DeleteServiceResponse)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/DeleteService", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) ListServices(ctx context.Context, in *ListServiceRequest, opts ...grpc.CallOption) (ControlDBService_ListServicesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ControlDBService_serviceDesc.Streams[1], c.cc, "/controldb_proto.ControlDBService/ListServices", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlDBServiceListServicesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControlDBService_ListServicesClient interface {
	Recv() (*Service, error)
	grpc.ClientStream
}

type controlDBServiceListServicesClient struct {
	grpc.ClientStream
}

func (x *controlDBServiceListServicesClient) Recv() (*Service, error) {
	m := new(Service)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controlDBServiceClient) CreateServiceAttr(ctx context.Context, in *ServiceAttr, opts ...grpc.CallOption) (*CreateServiceAttrResponse, error) {
	out := new(CreateServiceAttrResponse)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/CreateServiceAttr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) GetServiceAttr(ctx context.Context, in *ServiceAttrKey, opts ...grpc.CallOption) (*ServiceAttr, error) {
	out := new(ServiceAttr)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/GetServiceAttr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) DeleteServiceAttr(ctx context.Context, in *ServiceAttrKey, opts ...grpc.CallOption) (*DeleteServiceAttrResponse, error) {
	out := new(DeleteServiceAttrResponse)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/DeleteServiceAttr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) UpdateServiceAttr(ctx context.Context, in *UpdateServiceAttrRequest, opts ...grpc.CallOption) (*UpdateServiceAttrResponse, error) {
	out := new(UpdateServiceAttrResponse)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/UpdateServiceAttr", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) CreateVolume(ctx context.Context, in *Volume, opts ...grpc.CallOption) (*CreateVolumeResponse, error) {
	out := new(CreateVolumeResponse)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/CreateVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) GetVolume(ctx context.Context, in *VolumeKey, opts ...grpc.CallOption) (*Volume, error) {
	out := new(Volume)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/GetVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) DeleteVolume(ctx context.Context, in *VolumeKey, opts ...grpc.CallOption) (*DeleteVolumeResponse, error) {
	out := new(DeleteVolumeResponse)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/DeleteVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) ListVolumes(ctx context.Context, in *ListVolumeRequest, opts ...grpc.CallOption) (ControlDBService_ListVolumesClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_ControlDBService_serviceDesc.Streams[2], c.cc, "/controldb_proto.ControlDBService/ListVolumes", opts...)
	if err != nil {
		return nil, err
	}
	x := &controlDBServiceListVolumesClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ControlDBService_ListVolumesClient interface {
	Recv() (*Volume, error)
	grpc.ClientStream
}

type controlDBServiceListVolumesClient struct {
	grpc.ClientStream
}

func (x *controlDBServiceListVolumesClient) Recv() (*Volume, error) {
	m := new(Volume)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *controlDBServiceClient) UpdateVolume(ctx context.Context, in *UpdateVolumeRequest, opts ...grpc.CallOption) (*UpdateVolumeResponse, error) {
	out := new(UpdateVolumeResponse)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/UpdateVolume", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) CreateConfigFile(ctx context.Context, in *ConfigFile, opts ...grpc.CallOption) (*CreateConfigFileResponse, error) {
	out := new(CreateConfigFileResponse)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/CreateConfigFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) GetConfigFile(ctx context.Context, in *ConfigFileKey, opts ...grpc.CallOption) (*ConfigFile, error) {
	out := new(ConfigFile)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/GetConfigFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controlDBServiceClient) DeleteConfigFile(ctx context.Context, in *ConfigFileKey, opts ...grpc.CallOption) (*DeleteConfigFileResponse, error) {
	out := new(DeleteConfigFileResponse)
	err := grpc.Invoke(ctx, "/controldb_proto.ControlDBService/DeleteConfigFile", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ControlDBService service

type ControlDBServiceServer interface {
	CreateDevice(context.Context, *Device) (*CreateDeviceResponse, error)
	GetDevice(context.Context, *DeviceKey) (*Device, error)
	DeleteDevice(context.Context, *DeviceKey) (*DeleteDeviceResponse, error)
	ListDevices(*ListDeviceRequest, ControlDBService_ListDevicesServer) error
	CreateService(context.Context, *Service) (*CreateServiceResponse, error)
	GetService(context.Context, *ServiceKey) (*Service, error)
	DeleteService(context.Context, *ServiceKey) (*DeleteServiceResponse, error)
	ListServices(*ListServiceRequest, ControlDBService_ListServicesServer) error
	CreateServiceAttr(context.Context, *ServiceAttr) (*CreateServiceAttrResponse, error)
	GetServiceAttr(context.Context, *ServiceAttrKey) (*ServiceAttr, error)
	DeleteServiceAttr(context.Context, *ServiceAttrKey) (*DeleteServiceAttrResponse, error)
	UpdateServiceAttr(context.Context, *UpdateServiceAttrRequest) (*UpdateServiceAttrResponse, error)
	CreateVolume(context.Context, *Volume) (*CreateVolumeResponse, error)
	GetVolume(context.Context, *VolumeKey) (*Volume, error)
	DeleteVolume(context.Context, *VolumeKey) (*DeleteVolumeResponse, error)
	ListVolumes(*ListVolumeRequest, ControlDBService_ListVolumesServer) error
	UpdateVolume(context.Context, *UpdateVolumeRequest) (*UpdateVolumeResponse, error)
	CreateConfigFile(context.Context, *ConfigFile) (*CreateConfigFileResponse, error)
	GetConfigFile(context.Context, *ConfigFileKey) (*ConfigFile, error)
	DeleteConfigFile(context.Context, *ConfigFileKey) (*DeleteConfigFileResponse, error)
}

func RegisterControlDBServiceServer(s *grpc.Server, srv ControlDBServiceServer) {
	s.RegisterService(&_ControlDBService_serviceDesc, srv)
}

func _ControlDBService_CreateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).CreateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/CreateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).CreateDevice(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).GetDevice(ctx, req.(*DeviceKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeviceKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/DeleteDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).DeleteDevice(ctx, req.(*DeviceKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_ListDevices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListDeviceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlDBServiceServer).ListDevices(m, &controlDBServiceListDevicesServer{stream})
}

type ControlDBService_ListDevicesServer interface {
	Send(*Device) error
	grpc.ServerStream
}

type controlDBServiceListDevicesServer struct {
	grpc.ServerStream
}

func (x *controlDBServiceListDevicesServer) Send(m *Device) error {
	return x.ServerStream.SendMsg(m)
}

func _ControlDBService_CreateService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Service)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).CreateService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/CreateService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).CreateService(ctx, req.(*Service))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_GetService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).GetService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/GetService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).GetService(ctx, req.(*ServiceKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_DeleteService_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).DeleteService(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/DeleteService",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).DeleteService(ctx, req.(*ServiceKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_ListServices_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListServiceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlDBServiceServer).ListServices(m, &controlDBServiceListServicesServer{stream})
}

type ControlDBService_ListServicesServer interface {
	Send(*Service) error
	grpc.ServerStream
}

type controlDBServiceListServicesServer struct {
	grpc.ServerStream
}

func (x *controlDBServiceListServicesServer) Send(m *Service) error {
	return x.ServerStream.SendMsg(m)
}

func _ControlDBService_CreateServiceAttr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceAttr)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).CreateServiceAttr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/CreateServiceAttr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).CreateServiceAttr(ctx, req.(*ServiceAttr))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_GetServiceAttr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceAttrKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).GetServiceAttr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/GetServiceAttr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).GetServiceAttr(ctx, req.(*ServiceAttrKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_DeleteServiceAttr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ServiceAttrKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).DeleteServiceAttr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/DeleteServiceAttr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).DeleteServiceAttr(ctx, req.(*ServiceAttrKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_UpdateServiceAttr_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateServiceAttrRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).UpdateServiceAttr(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/UpdateServiceAttr",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).UpdateServiceAttr(ctx, req.(*UpdateServiceAttrRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_CreateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Volume)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).CreateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/CreateVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).CreateVolume(ctx, req.(*Volume))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_GetVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).GetVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/GetVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).GetVolume(ctx, req.(*VolumeKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_DeleteVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VolumeKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).DeleteVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/DeleteVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).DeleteVolume(ctx, req.(*VolumeKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_ListVolumes_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ListVolumeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControlDBServiceServer).ListVolumes(m, &controlDBServiceListVolumesServer{stream})
}

type ControlDBService_ListVolumesServer interface {
	Send(*Volume) error
	grpc.ServerStream
}

type controlDBServiceListVolumesServer struct {
	grpc.ServerStream
}

func (x *controlDBServiceListVolumesServer) Send(m *Volume) error {
	return x.ServerStream.SendMsg(m)
}

func _ControlDBService_UpdateVolume_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVolumeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).UpdateVolume(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/UpdateVolume",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).UpdateVolume(ctx, req.(*UpdateVolumeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_CreateConfigFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigFile)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).CreateConfigFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/CreateConfigFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).CreateConfigFile(ctx, req.(*ConfigFile))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_GetConfigFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigFileKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).GetConfigFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/GetConfigFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).GetConfigFile(ctx, req.(*ConfigFileKey))
	}
	return interceptor(ctx, in, info, handler)
}

func _ControlDBService_DeleteConfigFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ConfigFileKey)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControlDBServiceServer).DeleteConfigFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/controldb_proto.ControlDBService/DeleteConfigFile",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControlDBServiceServer).DeleteConfigFile(ctx, req.(*ConfigFileKey))
	}
	return interceptor(ctx, in, info, handler)
}

var _ControlDBService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "controldb_proto.ControlDBService",
	HandlerType: (*ControlDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDevice",
			Handler:    _ControlDBService_CreateDevice_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _ControlDBService_GetDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _ControlDBService_DeleteDevice_Handler,
		},
		{
			MethodName: "CreateService",
			Handler:    _ControlDBService_CreateService_Handler,
		},
		{
			MethodName: "GetService",
			Handler:    _ControlDBService_GetService_Handler,
		},
		{
			MethodName: "DeleteService",
			Handler:    _ControlDBService_DeleteService_Handler,
		},
		{
			MethodName: "CreateServiceAttr",
			Handler:    _ControlDBService_CreateServiceAttr_Handler,
		},
		{
			MethodName: "GetServiceAttr",
			Handler:    _ControlDBService_GetServiceAttr_Handler,
		},
		{
			MethodName: "DeleteServiceAttr",
			Handler:    _ControlDBService_DeleteServiceAttr_Handler,
		},
		{
			MethodName: "UpdateServiceAttr",
			Handler:    _ControlDBService_UpdateServiceAttr_Handler,
		},
		{
			MethodName: "CreateVolume",
			Handler:    _ControlDBService_CreateVolume_Handler,
		},
		{
			MethodName: "GetVolume",
			Handler:    _ControlDBService_GetVolume_Handler,
		},
		{
			MethodName: "DeleteVolume",
			Handler:    _ControlDBService_DeleteVolume_Handler,
		},
		{
			MethodName: "UpdateVolume",
			Handler:    _ControlDBService_UpdateVolume_Handler,
		},
		{
			MethodName: "CreateConfigFile",
			Handler:    _ControlDBService_CreateConfigFile_Handler,
		},
		{
			MethodName: "GetConfigFile",
			Handler:    _ControlDBService_GetConfigFile_Handler,
		},
		{
			MethodName: "DeleteConfigFile",
			Handler:    _ControlDBService_DeleteConfigFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ListDevices",
			Handler:       _ControlDBService_ListDevices_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListServices",
			Handler:       _ControlDBService_ListServices_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ListVolumes",
			Handler:       _ControlDBService_ListVolumes_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "controldb.proto",
}

func init() { proto.RegisterFile("controldb.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1098 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0x5f, 0x73, 0xdb, 0x44,
	0x10, 0x8f, 0x9d, 0xd4, 0x8e, 0xd7, 0x76, 0x49, 0xae, 0xd0, 0x0a, 0x15, 0x4a, 0x47, 0x34, 0x9d,
	0x26, 0x0f, 0xa1, 0x04, 0x5a, 0x1e, 0x99, 0x26, 0x86, 0x4e, 0x06, 0xd2, 0x29, 0xf6, 0xa4, 0x0f,
	0x4c, 0x99, 0x8c, 0x6c, 0x5f, 0x88, 0x06, 0xd9, 0x32, 0x3a, 0x39, 0x1d, 0xf8, 0x08, 0xbc, 0xf2,
	0x6d, 0x78, 0xe5, 0x83, 0xc1, 0xde, 0x1f, 0xfd, 0x39, 0x9d, 0x4e, 0xf6, 0x10, 0xde, 0xa4, 0xbd,
	0xdd, 0xdf, 0xed, 0xfd, 0xee, 0x77, 0xbb, 0x0b, 0xef, 0x4d, 0xa2, 0x79, 0x12, 0x47, 0xe1, 0x74,
	0x7c, 0xb8, 0x88, 0xa3, 0x24, 0x22, 0xb9, 0xe1, 0x42, 0x18, 0xbc, 0x33, 0xe8, 0x0c, 0xe8, 0x75,
	0x30, 0xa1, 0xdf, 0xd1, 0xdf, 0xc8, 0x43, 0xe8, 0x4e, 0xc2, 0x25, 0x4b, 0x68, 0xfc, 0xca, 0x9f,
	0x51, 0xa7, 0xf1, 0xb0, 0xf1, 0xa4, 0x33, 0x2c, 0x9a, 0xc8, 0x03, 0x80, 0xa9, 0x70, 0x17, 0x0e,
	0x4d, 0xe1, 0x50, 0xb0, 0x78, 0x21, 0xb4, 0x24, 0xdc, 0xcd, 0xb1, 0x38, 0x02, 0xa3, 0x71, 0xe6,
	0xb0, 0x29, 0x11, 0x0a, 0x26, 0xef, 0x2e, 0xbc, 0x7f, 0x12, 0x53, 0x3f, 0xa1, 0x72, 0xcf, 0x21,
	0x65, 0x8b, 0x68, 0xce, 0x84, 0x7d, 0x40, 0x43, 0x6a, 0xd8, 0xbf, 0x06, 0x78, 0x11, 0x86, 0xd2,
	0xc8, 0xc8, 0xe7, 0xd0, 0x96, 0xbb, 0x31, 0xcc, 0x6e, 0xf3, 0x49, 0xf7, 0xe8, 0xde, 0x61, 0x89,
	0x9d, 0x43, 0x15, 0x9f, 0xfa, 0x79, 0xcf, 0x60, 0xf7, 0xfb, 0x80, 0x25, 0x29, 0xec, 0xaf, 0x4b,
	0xca, 0x92, 0xd5, 0x27, 0xf5, 0x5e, 0x03, 0x8c, 0x64, 0xda, 0xeb, 0xb1, 0x5c, 0x3a, 0x79, 0xd3,
	0x3c, 0x79, 0x04, 0x6d, 0x85, 0xf8, 0x7f, 0xc0, 0x15, 0x3c, 0xce, 0xcf, 0x4f, 0x07, 0x25, 0xaa,
	0xb9, 0xc9, 0xbb, 0x07, 0x1f, 0x48, 0xaa, 0xd5, 0xb6, 0x19, 0xa7, 0xb8, 0x20, 0xb9, 0x2e, 0x2f,
	0x9c, 0x40, 0x17, 0xc9, 0x56, 0x56, 0x46, 0xbe, 0x84, 0x6d, 0x85, 0x97, 0xd2, 0xed, 0x18, 0x74,
	0xa7, 0x10, 0x99, 0xa7, 0xf7, 0x1c, 0x08, 0x27, 0x3c, 0xc3, 0x5e, 0x97, 0xf1, 0x23, 0xb8, 0xad,
	0x62, 0x5e, 0x24, 0x49, 0xac, 0x58, 0x2f, 0x1e, 0xb1, 0x61, 0x1e, 0xf1, 0xcf, 0x4d, 0xe8, 0x16,
	0x82, 0x56, 0x47, 0x90, 0x47, 0xd0, 0x57, 0xbf, 0xa3, 0xc4, 0x4f, 0x96, 0x4c, 0x51, 0xab, 0x1b,
	0x89, 0x07, 0xbd, 0xd0, 0x67, 0xc9, 0x59, 0x34, 0x0d, 0x2e, 0x03, 0x3a, 0x15, 0xec, 0x6e, 0x0e,
	0x35, 0x1b, 0x71, 0x61, 0x3b, 0xa6, 0x8b, 0x30, 0x98, 0xf8, 0xcc, 0xd9, 0x12, 0xeb, 0xd9, 0x3f,
	0x8f, 0xbf, 0x8e, 0xc2, 0xe5, 0x8c, 0x8e, 0x82, 0xdf, 0xe9, 0xcb, 0x63, 0xe7, 0x96, 0x8c, 0x2f,
	0xda, 0xca, 0x8c, 0xb4, 0x56, 0x8a, 0xa0, 0x6d, 0x8a, 0x40, 0x7f, 0x8f, 0xdb, 0xc6, 0x7b, 0x7c,
	0x0a, 0x77, 0xae, 0x7c, 0x36, 0x4a, 0xe2, 0x60, 0x92, 0x9c, 0xd1, 0xd9, 0x98, 0xc6, 0xec, 0x2a,
	0x58, 0x38, 0x1d, 0x74, 0xdc, 0x1e, 0x56, 0x2d, 0x09, 0xc4, 0x68, 0xe6, 0x07, 0x73, 0x81, 0x08,
	0x0a, 0x31, 0xb3, 0xf0, 0x93, 0x5d, 0x45, 0x98, 0xe1, 0xf4, 0xc7, 0x68, 0x4e, 0x91, 0xe2, 0xae,
	0xf0, 0xd0, 0x6c, 0xde, 0x7d, 0xf8, 0x50, 0x13, 0x1e, 0xbf, 0x9a, 0x4c, 0x63, 0xb8, 0xa8, 0x89,
	0x4f, 0x5b, 0xfc, 0xa3, 0x01, 0xce, 0xf9, 0x62, 0x5a, 0x0e, 0x95, 0x12, 0x7a, 0x0e, 0x6d, 0x14,
	0x1e, 0xb7, 0x88, 0x8b, 0xed, 0x1e, 0x7d, 0x64, 0x53, 0xa3, 0x88, 0x4a, 0x9d, 0x79, 0xdc, 0x9c,
	0xbe, 0x13, 0x71, 0xcd, 0x75, 0xe2, 0x94, 0x33, 0xcf, 0xb4, 0x22, 0x17, 0x95, 0xe9, 0x29, 0x74,
	0xde, 0x88, 0xdb, 0x5c, 0x4b, 0xa8, 0x5c, 0x2c, 0xf2, 0xf2, 0x71, 0x59, 0x2a, 0x2e, 0xfb, 0xf7,
	0xfe, 0x69, 0x42, 0x4b, 0x62, 0xdd, 0x0c, 0x68, 0x2d, 0xd5, 0xea, 0x8a, 0xd9, 0x32, 0x14, 0x83,
	0xef, 0xc3, 0xbf, 0xf6, 0x83, 0xd0, 0x1f, 0x87, 0x94, 0x5f, 0xa7, 0x90, 0x2e, 0xbe, 0x0f, 0xcd,
	0x48, 0xee, 0x42, 0x2b, 0xf1, 0xd9, 0x2f, 0x98, 0x83, 0x94, 0xad, 0xfa, 0xe3, 0x7a, 0xe3, 0xd4,
	0xa2, 0x58, 0x68, 0x7c, 0x3a, 0x67, 0x89, 0x3f, 0x9f, 0xf0, 0x44, 0xa5, 0x72, 0xab, 0x96, 0xc8,
	0x01, 0xec, 0xf0, 0xe3, 0x69, 0xee, 0x52, 0xc7, 0x86, 0x9d, 0xe7, 0x3e, 0x13, 0x4a, 0x15, 0xb9,
	0x77, 0x64, 0xee, 0xb9, 0x85, 0x7c, 0x05, 0x6d, 0xdc, 0xe2, 0x32, 0xf8, 0x99, 0xa1, 0x70, 0x79,
	0xb9, 0xfa, 0xd8, 0xb8, 0x68, 0xa9, 0xf4, 0x13, 0xe1, 0x35, 0x4c, 0xbd, 0xf3, 0xa6, 0x24, 0xaf,
	0xc1, 0x6c, 0x4a, 0x25, 0xbb, 0xea, 0x29, 0xa9, 0x35, 0xab, 0x70, 0x2b, 0xaa, 0xd5, 0x3b, 0xb8,
	0x23, 0x05, 0xa5, 0x07, 0x7e, 0x06, 0x2d, 0xcc, 0x10, 0x6d, 0x4a, 0xd6, 0x66, 0x4f, 0x53, 0xfe,
	0xca, 0x8d, 0x07, 0xa0, 0x46, 0x79, 0x40, 0x73, 0x45, 0x80, 0x74, 0xe3, 0xe7, 0xd0, 0x37, 0x56,
	0xe7, 0x78, 0x0b, 0xbd, 0x22, 0x21, 0x5c, 0x5c, 0x97, 0x41, 0x48, 0x0b, 0x15, 0x3a, 0xfb, 0xe7,
	0x57, 0xce, 0xbf, 0x33, 0xd9, 0xa9, 0x3f, 0xe2, 0x40, 0x9b, 0x7f, 0x9d, 0x0d, 0x9e, 0xa9, 0x1e,
	0x94, 0xfe, 0xe2, 0x13, 0xe9, 0x4b, 0xdc, 0x6f, 0xd1, 0xb0, 0xde, 0x33, 0xb1, 0x6c, 0xe2, 0xfd,
	0xd5, 0x00, 0xc8, 0xb1, 0xfe, 0x3b, 0x90, 0x3d, 0x5b, 0xed, 0xec, 0x5b, 0xa5, 0xb3, 0x97, 0x1f,
	0xd6, 0xad, 0x8a, 0x87, 0xe5, 0x08, 0xf1, 0x25, 0x74, 0x9e, 0xa8, 0x37, 0x91, 0xfe, 0x7a, 0x2e,
	0x38, 0x52, 0x5d, 0xf9, 0x09, 0xb2, 0x1b, 0xc0, 0x35, 0xa9, 0x30, 0x73, 0xed, 0xe8, 0xef, 0x3e,
	0xec, 0x9c, 0xc8, 0x8b, 0x1d, 0x1c, 0xa7, 0xa3, 0xc3, 0x6b, 0xe8, 0x15, 0xe7, 0x27, 0x62, 0x1b,
	0x80, 0xdc, 0x3d, 0x63, 0xa1, 0x72, 0xee, 0xda, 0x20, 0xc7, 0xd0, 0x79, 0x49, 0xd5, 0x7c, 0x44,
	0x5c, 0x0b, 0x1c, 0x5e, 0x9f, 0x6b, 0xdb, 0x0a, 0x31, 0x46, 0xd0, 0x2b, 0x4e, 0x6f, 0xb5, 0x30,
	0x7b, 0x15, 0x6b, 0x15, 0x83, 0xdf, 0x06, 0x79, 0x05, 0xdd, 0x7c, 0x72, 0xc3, 0x9e, 0x6a, 0xc4,
	0x19, 0x73, 0x5d, 0x4d, 0x8a, 0x4f, 0x1b, 0x98, 0x64, 0x5f, 0x6b, 0x4b, 0xc4, 0x3a, 0xcd, 0xb8,
	0x8f, 0x2d, 0xe4, 0x95, 0x07, 0xa6, 0x0d, 0xf2, 0x0d, 0x00, 0xb2, 0x97, 0x22, 0xde, 0xb7, 0x21,
	0xf2, 0x83, 0x5b, 0xb7, 0x43, 0x98, 0x37, 0xd0, 0xd7, 0xba, 0x62, 0x3d, 0xd2, 0x63, 0x0b, 0x85,
	0x66, 0x7a, 0x3f, 0x40, 0xaf, 0x30, 0x8c, 0x31, 0xf2, 0x69, 0x25, 0x89, 0xfa, 0xac, 0x56, 0x97,
	0x28, 0xd2, 0x78, 0x01, 0xbb, 0x46, 0x77, 0x27, 0xb5, 0x2d, 0xd5, 0x3d, 0xa8, 0xa7, 0x53, 0x6b,
	0xac, 0x3c, 0xe7, 0xdb, 0x39, 0xa5, 0x02, 0xfd, 0x93, 0x3a, 0x74, 0x4e, 0x48, 0xed, 0xf6, 0x08,
	0x39, 0x86, 0x5d, 0x63, 0xe8, 0x58, 0x8d, 0x7a, 0x50, 0x4f, 0x73, 0x29, 0xed, 0x10, 0x76, 0x8d,
	0x71, 0x81, 0xec, 0x1b, 0x10, 0xb6, 0xf1, 0xa6, 0x62, 0x37, 0xfb, 0xf4, 0xb1, 0x91, 0xd7, 0x01,
	0x35, 0x39, 0xd8, 0x7a, 0x80, 0xb5, 0x0e, 0x94, 0x5a, 0x41, 0x5a, 0x07, 0x14, 0x9c, 0x6b, 0x81,
	0xab, 0xae, 0x03, 0x72, 0xad, 0x58, 0x07, 0xd6, 0x80, 0xb1, 0xd5, 0x01, 0x23, 0x31, 0x55, 0x07,
	0xa4, 0xdd, 0x56, 0x07, 0xb4, 0x96, 0x5a, 0x93, 0x22, 0x0a, 0xf8, 0x27, 0xe8, 0x15, 0xbb, 0x21,
	0x79, 0x64, 0x21, 0x5e, 0x87, 0xdc, 0x5b, 0xe1, 0x95, 0xa5, 0xfb, 0x16, 0xab, 0x76, 0xa9, 0xdc,
	0x57, 0xbc, 0xe6, 0x7c, 0xd1, 0xdd, 0xb7, 0xdc, 0x50, 0x45, 0xbb, 0xe0, 0x64, 0xf4, 0xf1, 0x96,
	0x0a, 0xd0, 0x0f, 0x6a, 0xa0, 0x39, 0xcd, 0x75, 0x5b, 0x23, 0xde, 0x05, 0xec, 0x94, 0x1b, 0xd0,
	0x4a, 0xc8, 0x7d, 0xcb, 0xcd, 0x55, 0x25, 0x3c, 0x6e, 0x09, 0x8f, 0x2f, 0xfe, 0x0d, 0x00, 0x00,
	0xff, 0xff, 0xd1, 0xe2, 0x2a, 0x88, 0xd8, 0x10, 0x00, 0x00,
}
