#!/bin/sh
set -e

# run all unit tests
gotest="go test -short -cover"

$gotest ./api/...
$gotest ./catalog/...
$gotest ./db/...
$gotest ./utils/...
$gotest ./containersvc/...
$gotest ./dns/...
$gotest ./managesvc/...
$gotest ./log/...

# docker volume and server unit tests use loop device, root permission is required.
sudo -E $gotest ./plugins/...

# to exclude ec2 test, switch to run server unit test only
sudo -E $gotest ./server/...
#cd server; sudo -E go test; cd -
